name: eggnogmapper-emapper
description: |
  Search for orthologous proteins, and annotate functional domains and
    functional description based on orthology.

keywords:
  - genome
  - functional-annotation
  - orthology
  - protein
  - domain

tools:
  - eggnog-mapper:
      description: "EggNOG-mapper is a tool for genome-wide functional annotation through orthology assignment
      homepage: "http://eggnog-mapper.embl.de/"
      documentation: "https://github.com/jhcepas/eggnog-mapper/wiki"
      tool_dev_url: "https://github.com/eggnogdb/eggnog-mapper"
      doi: "10.1093/nar/gky1085"
      licence: ["AGPL-3.0"]

input:
  - fasta:
      type: file
      description: Input fasta file containing query sequences
      pattern: "*.{fa,fasta}"

output:
  - annotations:
        type: file
        description: File containing functional annotations
        pattern: "*.{annotations.txt}"
  - seed_orthologs:
        type: file
        description: File containing seed orthologs
        pattern: "*.{seed_orthologs.txt}"
  - decorated_gff:
        type: file
        description: File containing decorated gff
        pattern: "*.{decorated.gff}"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@kherronism"
