name: picard_collectalignmentsummarymetrics
description: Collect summary of alignment metrics from a SAM or BAM file
keywords:
  - alignment
  - metrics
  - statistics
  - sam
  - bam
tools:
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: SAM/BAM file
      pattern: "*.{sam,bam}"
  - fasta:
      type: file
      description: Genome fasta file

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - metrics:
      type: file
      description: Alignment metrics files generated by picard
      pattern: "*.alignment_summary_metrics"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@kherronism"
