name: braker3
description: |
    Gene prediction in novel genomes using RNA-seq and protein homology information
keywords:
  - genome
  - annotation
tools:
  - braker3:
      description: "BRAKER3 is a pipeline for fully automated prediction of
          protein coding gene structures using protein and RNA-seq and protein homology
          information"
      homepage: "https://github.com/Gaius-Augustus/BRAKER"
      documentation: "https://github.com/Gaius-Augustus/BRAKER"
      tool_dev_url: "https://github.com/Gaius-Augustus/BRAKER"
      doi: "10.13140/RG.2.2.20047.36004"
      licence: ["Artistic-1.0"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Genome assembly fasta
      pattern: "*.{fasta,fa,fas,faa,fna}"
  - rnaseq_sets_ids:
      type: file
      description: IDs of RNA-seq datasets to be passed to --rnaseq_sets_ids
  - rnaseq_sets_dirs:
      type: file
      description: Directories of RNA-seq datasets to be passed to --rnaseq_sets_dirs
  - bam:
      type: file
      description: BAM file of RNA-seq data to be passed to --bam
      pattern: "*.bam"
  - proteins:
      type: file
      description: Protein evidence to be passed to --proteins
      pattern: "*.{fasta,fa,fas,faa}"
  - hintsfile:
      type: file
      description: Hints file to be passed to --hintsfile
      pattern: "*.{gff, gtf, gff3}"
output:
  - gtf:
      type: file
      description: Annotation file in GTF format as output by BRAKER3
      pattern: "*.{gtf}"
  - cds:
      type: file
      description: Coding sequence file as output by BRAKER3
      pattern: "*.{codingseq}"
  - aa:
      type: file
      description: Protein sequence file as output by BRAKER3
      pattern: "*.{aa}"
  - hintsfile:
      type: file
      description: Hints file as output by BRAKER3
      pattern: "*hintsfile.{gff}"
  - gff3:
      type: file
      description: Annotation file in GFFS format
      pattern: "*.{gff3}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@kherronism"
maintainers:
  - "@kherronism"
