name: braker3
description: |
    Gene prediction in novel genomes using RNA-seq and protein homology information
keywords:
  - genome
  - annotation

tools:
  - braker3:
      description: "BRAKER3 is a pipeline for fully automated prediction of
          protein coding gene structures using protein and RNA-seq and protein homology
          information"
      homepage: "https://github.com/Gaius-Augustus/BRAKER"
      documentation: "https://github.com/Gaius-Augustus/BRAKER"
      tool_dev_url: "https://github.com/Gaius-Augustus/BRAKER"
      doi: "10.13140/RG.2.2.20047.36004"
      licence: ["Artistic-1.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - assembly:
      type: file
      description: Genome assembly
      pattern: "*.{fasta,fa,fas,faa,fna}"

output:
  - gtf:
      type: file
      description: Gene transfer format file as output by BRAKER3
      pattern: "*.{gtf}"
  - cds:
      type: file
      description: Coding sequence file as output by BRAKER3
      pattern: "*.{codingseq}"
  - aa:
      type: file
      description: Protein sequence file as output by BRAKER3
      pattern: "*.{aa}"
  - hintsfile:
      type: file
      description: Hints file as output by BRAKER3
      pattern: "*hintsfile.{gff}"
  - gff3:
      type: file
      description: GFF3 file as output by BRAKER3
      pattern: "*.{gff3}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@kherronism"
