name: agat_keeplongestisoform
description: |
  Uses the AGAT tool sp_keep_longest_isoform to keep the longest isoform of each
  gene in a GFF/GTF file.
keywords:
  - genome
  - gff
  - gtf

tools:
  - agat:
      description: "AGAT is a toolkit for manipulation and getting information from GFF/GTF files"
      homepage: "https://github.com/NBISweden/AGAT"
      documentation: "https://agat.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/NBISweden/AGAT"
      doi: "10.5281/zenodo.3552717"
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - gff:
      type: file
      description: Annotation file in GFF3/GTF format
      pattern: "*.{gff, gtf, gff3}"

output:
  - longest_isoform_gff:
      type: file
      description: Annotation file filtered for longest isoforms
      pattern: "*.{gff}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@kherronism"
